alibaba:
  cloud:
    bucket-name: wdproject2
    access-key: LTAI5t8gpxPTCR6W58RnZq4u
    secret-key: mVPbpbxia0JQotb7HyJAREV8QUuq8h
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
    sms:
      sign-name: 王道训练营
      template-code: SMS_173765187