spring:
  redis:
    database: 0
    host: jfl.kiroe.cn
    port: 6379
    password: 123321
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
    connect-timeout: 30000ms
